FROM ruby:2.3.7-alpine
ENV APP_HOME /app
ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN apk add --update --no-cache \
    build-base \
    ruby \
    ruby-bundler \
    ruby-dev \
    ruby-io-console \
    ruby-json \
    ruby-rake \
    && gem install bundler --no-ri --no-rdoc

COPY Gemfile* $APP_HOME/
RUN bundle install

COPY . $APP_HOME
CMD ["puma"]
