---
- name: Deploy apps
  hosts: app
  vars:
    deploy_user: appuser
  tags: deploy-tag

  tasks:
    - name: Clone reddit-app from github
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith

    - name: Install bundle dependencies
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"
      notify: Restart Puma

  handlers:
   - name: Restart Puma
     become: true
     service: name=puma state=restarted
